### ISSUE TITLE
No module named 'layers'

### ISSUE THREAD

**Issue by luoyangwei** [nywang16/Pixel2Mesh#113]
刚接触tensorflow 请别嫌弃问题简单嫌我烦😭

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/31927848/199708313-db1f02a5-bb9d-42d6-8a6e-d3fc42f1dea0.png">

报错：
ModuleNotFoundError: No module named 'layers'

环境：
python 3.9
tflearn 0.5.0
tensorflow-macos 2.10.0
macOS Ventura 13.0 (Apple M1)

**Comment by pengzhao-life** [comment]
Hi, I got the same error. I simply add package name as prefix, i.e. change line 19 to 'from p2m.layers import *', and it worked for me.

**Comment by luoyangwei** [comment]
> Hi, I got the same error. I simply add package name as prefix, i.e. change line 19 to 'from p2m.layers import *', and it worked for me.

thanks!

**Comment by OmariNewAeon** [comment]
Traceback (most recent call last):
  File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\demo.py", line 20, in <module>
    from p2m.api import GCN
  File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\p2m\api.py", line 19, in <module>
    from p2m.layers import *
  File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\p2m\layers.py", line 21, in <module>
    from inits import *
ModuleNotFoundError: No module named 'inits'

**Comment by lechogt** [comment]
> Traceback (most recent call last): File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\demo.py", line 20, in from p2m.api import GCN File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\p2m\api.py", line 19, in from p2m.layers import * File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\p2m\layers.py", line 21, in from inits import * ModuleNotFoundError: No module named 'inits'

i got the same quesion how to solve it ?

**Comment by shayansep** [comment]
import it as
from .layers import *
not just layers(put a dot behind layers)

**Comment by shayansep** [comment]
> > Traceback (most recent call last): File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\demo.py", line 20, in from p2m.api import GCN File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\p2m\api.py", line 19, in from p2m.layers import * File "C:\Users\mohmm\OneDrive\Desktop\28_omari\arafat\Pixel2Mesh\p2m\layers.py", line 21, in from inits import * ModuleNotFoundError: No module named 'inits'
> 
> i got the same quesion how to solve it ?

---------------------------------

you also put a dot behind .inits like:
from .inits import *

open layers.py and edit it
