### ISSUE TITLE
tf_nndistance_so.so not found

### ISSUE THREAD

**Issue by Timyu957** [nywang16/Pixel2Mesh#119]
When I was training,Display error
Traceback (most recent call last):
  File "D:\pycharm\Pixel2Mesh-master1\Pixel2Mesh-master\train.py", line 21, in <module>
    from p2m.models import GCN
  File "D:\pycharm\Pixel2Mesh-master1\Pixel2Mesh-master\p2m\models.py", line 20, in <module>
    from p2m.losses import *
  File "D:\pycharm\Pixel2Mesh-master1\Pixel2Mesh-master\p2m\losses.py", line 18, in <module>
    from p2m.chamfer import *
  File "D:\pycharm\Pixel2Mesh-master1\Pixel2Mesh-master\p2m\chamfer.py", line 21, in <module>
    nn_distance_module = tf.load_op_library('D:/pycharm/Pixel2Mesh-master1/Pixel2Mesh-master/external/tf_nndistance_so.so')
  File "D:\anaconda\envs\pix9\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: D:\pycharm\Pixel2Mesh-master1\Pixel2Mesh-master\external\tf_nndistance_so.so not found

Display this file tf_ Nndistance_ So.so cannot be found
But this article does exist, and I haven't changed its name either

**Comment by Timyu957** [comment]
And my path is definitely not wrong

**Comment by sksnb** [comment]
Hello, I also had the same issue, did you fix this issue
