### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by shihanyu** [nywang16/Pixel2Mesh#13]
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 3, in <module>
    from pixel2mesh.losses import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 2, in <module>
    from pixel2mesh.cd_dist import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/cd_dist.py", line 3, in <module>
    nn_distance_module=tf.load_op_library('./cd_dist.so')
  File "/home/shihanyu/.conda/envs/py277/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.8.0: cannot open shared object file: No such file or directory

**Comment by shihanyu** [comment]
I followed all your instructuons and made all the steps right before excute the demo.py. and I get these mistakes. Hope you can help me.

**Comment by AmyWan** [comment]
Ｉ　also has　the same question.like this:

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    from models import GCN
  File "/home/amy/Desktop/181008/Pixel2Mesh-master/pixel2mesh/models.py", line 3, in <module>
    from losses import *
  File "/home/amy/Desktop/181008/Pixel2Mesh-master/pixel2mesh/losses.py", line 2, in <module>
    from cd_dist import *
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
hope to help me

**Comment by M4gicT0** [comment]
You haven't install CUDA (8) apparently.

**Comment by AmyWan** [comment]
hi @M4gicT0 ，i have installed tf1.3,cuda8,cudnn6.but it has error like this.@luosihao And how I build cd_dist.so,couuld you like to tell me the details?
Traceback (most recent call last):   
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  File "/home/amywan/Desktop/pixel2mesh/models.py", line 3, in <module>
    from pixel2mesh.losses import *
  File "/home/amywan/Desktop/pixel2mesh/losses.py", line 2, in <module>
    from pixel2mesh.new import *
  File "/home/amywan/Desktop/pixel2mesh/new.py", line 3, in <module>
    nn_distance_module=tf.load_op_library('./cdc.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./cdc.so: cannot open shared object file: No such file or directory

**Comment by tingfengwanxiao** [comment]
do you have the successfully runed demo,can you share to me ,I meet many issure in grammar.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
