### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qui22** [nywang16/Pixel2Mesh#15]
I encountered this problem.
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    vert = sess.run(model.output3, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: <excephtion str() failed>

Did someone encounter this problem? thanks!

**Comment by walsvid** [comment]
The problem may be related to pre-trained model loading. Please check you have pretrained ckeckpoint file in correct directory and you have correct version of requirement libraries.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
