### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow8OpKernelE_

### ISSUE THREAD

**Issue by thanhkien84** [nywang16/Pixel2Mesh#32]
While running the demo code:
_python demo.py --image utils/examples/plane.png_ 

I got this error:
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 3, in <module>
    from pixel2mesh.losses import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 2, in <module>
    from pixel2mesh.cd_dist import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/cd_dist.py", line 3, in <module>
    nn_distance_module=tf.load_op_library('./external/tf_nndistance_so.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./external/tf_nndistance_so.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

Does anyone experience this?
My specs: Ubuntu 18.04, CUDA 10.0, CuDNN 7.4, Tensorflow 1.12, OpenCV 3.4.3.

**Comment by rubilin** [comment]
I also encountered this situation, Have you solved it?My specs: Ubuntu16.04 ,Tensorflow 1.12，opencv3.4.0

**Comment by rubilin** [comment]
You can refer to this URL：https://www.cnblogs.com/danpe/p/7825357.html，
Because the TF_LIB compilation parameter is missing from the makefile，You should modify this file，
I add TF_LIB =/usr/local/lib/python2.7/dist-packages/tensorflow
I modify :tf_nndistance_so.so: tf_nndistance_g.cu.o tf_nndistance.cpp
	g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I $(tensorflow) -lcudart -L $(cudalib) -O2 -L $(TF_LIB) -ltensorflow_framework -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by nitthilan** [comment]
I made the above change and still get the same error. Did anyone find a fix?

**Comment by hguomin** [comment]
> I made the above change and still get the same error. Did anyone find a fix?

did you install tensorflow with conda? if so, try to create a new env and install tf with pip, then this issue shall be fixed

**Comment by abadcd** [comment]
@nitthilan I also made the above changes but encountered the same error. Have you fixed it?

**Comment by sunayana** [comment]
I have the same issue in: 
Ubuntu 20.04
Using python3.8 and pip
I do not have a GPU
