### ISSUE TITLE
InvalidArgumentError (see above for traceback): indices[0,7] = -1 is not in [0, 157)

### ISSUE THREAD

**Issue by abadcd** [nywang16/Pixel2Mesh#39]
When I downloaded the ShapeNet.tar file, I decompressed it according to the document prompt. But because of my computer's performance problems, I didn't use ShapeNet.tar to perform Python train.py operations. I took only a part of ShapeNet. tar's decompressed content and trained it. But when I executed Python train.py, I was perplexed by the following mistakes. Please help me if you can.

1. Model restored from file: utils/checkpoint/gcn.ckpt
2. Traceback (most recent call last):
3. File "train.py", line 101, in <module>
4. _, dists,out1,out2,out3 = sess.run([model.opt_op,model.loss,model.output1,model.output2,model.output3], feed_dict=feed_dict)
5. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
6. run_metadata_ptr)
7. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
8. feed_dict_tensor, options, run_metadata)
9. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
10. run_metadata)
11. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
12. raise type(e)(node_def, op, message)
13. tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,7] = -1 is not in [0, 157)
14. [[Node: GatherV2_12 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](concat_2, strided_slice_15, gradients/graphconvolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul_grad/GatherV2/axis)]]
15. 
16. Caused by op u'GatherV2_12', defined at:
17. File "train.py", line 47, in <module>
18. model = GCN(placeholders, logging=True)
19. File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 108, in __init__
20. self.build()
21. File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 74, in build
22. self._loss()
23. File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 118, in _loss
24. self.loss += .2*laplace_loss(self.inputs, self.output1, self.placeholders, 1)
25. File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 16, in laplace_loss
26. lap1 = laplace_coord(pred1, placeholders, block_id)
27. File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 10, in laplace_coord
28. laplace = tf.reduce_sum(tf.gather(vertex, indices), 1)
29. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2659, in gather
30. return gen_array_ops.gather_v2(params, indices, axis, name=name)
31. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3142, in gather_v2
32. "GatherV2", params=params, indices=indices, axis=axis, name=name)
33. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
34. op_def=op_def)
35. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
36. return func(*args, **kwargs)
37. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
38. op_def=op_def)
39. File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
40. self._traceback = tf_stack.extract_stack()
41. 
42. InvalidArgumentError (see above for traceback): indices[0,7] = -1 is not in [0, 157)
43. [[Node: GatherV2_12 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](concat_2, strided_slice_15, gradients/graphconvolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul_grad/GatherV2/axis)]]

**Comment by hguomin** [comment]
I have the same issue, have you fixed it?

**Comment by abadcd** [comment]
@hguomin You try to modify the x2 = tf.ceil(x) and y2 = tf.ceil(y) in the project method in the layer.py file to behave as follows:
    x2 = tf.minimum(tf.ceil(x), tf.cast(tf.shape(img_feat)[0], tf.float32) - 1)
    y2 = tf.minimum(tf.ceil(y), tf.cast(tf.shape(img_feat)[1], tf.float32) - 1)

**Comment by abadcd** [comment]
@hguomin https://github.com/nywang16/Pixel2Mesh/issues/23

**Comment by hguomin** [comment]
> @hguomin #23

@abadcd Thank you!!!

**Comment by Weipeilang** [comment]
I met the same problem and installed the version of GPU.However,it is still not work.Any one can help me?

**Comment by gopikrishnachaganti** [comment]
try restarting your machine after installing the GPU drivers. it might help.

**Comment by Weipeilang** [comment]
Thank you for replying.I did what you said,but it didn't work at all.Do you still have other ways?Or can you send me you code? 




------------------ 原始邮件 ------------------
发件人: "gopikrishnachaganti"<notifications@github.com>;
发送时间: 2019年5月19日(星期天) 凌晨1:13
收件人: "nywang16/Pixel2Mesh"<Pixel2Mesh@noreply.github.com>;
抄送: "If you,if I"<2546954766@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [nywang16/Pixel2Mesh] InvalidArgumentError (see above fortraceback): indices[0,7] = -1 is not in [0, 157) (#39)




try restarting your machine after installing the GPU drivers. it might help.

**Comment by xiayizhan2017** [comment]
@Weipeilang 
I just install end the GPU version of tensorflow,but it still having this problem.
Have you solved it yet?

**Comment by tjluozhongjin** [comment]
As is explain in the [tensorflow document](https://www.tensorflow.org/api_docs/python/tf/gather_nd)：Note that on CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, a 0 is stored in the corresponding output value. 

And it also discuss on [this issue](https://github.com/tensorflow/tensorflow/issues/15091) .

One solution of this problem is changing the function `project` in the `layers.py` as follows:

```
def project(img_feat, x, y, dim):
    x1 = tf.floor(x)
    x2 = tf.ceil(x)
    y1 = tf.floor(y)
    y2 = tf.ceil(y)

    # add a padding to img_feat
    paddings = tf.constant([[0, 1], [0, 1], [0, 0]])
    img_feat = tf.pad(img_feat, paddings, 'CONSTANT')

    Q11 = tf.gather_nd(img_feat, tf.stack([tf.cast(x1, tf.int32), tf.cast(y1, tf.int32)], 1))
    Q12 = tf.gather_nd(img_feat, tf.stack([tf.cast(x1, tf.int32), tf.cast(y2, tf.int32)], 1))
    Q21 = tf.gather_nd(img_feat, tf.stack([tf.cast(x2, tf.int32), tf.cast(y1, tf.int32)], 1))
    Q22 = tf.gather_nd(img_feat, tf.stack([tf.cast(x2, tf.int32), tf.cast(y2, tf.int32)], 1))

    weights = tf.multiply(tf.subtract(x2, x), tf.subtract(y2, y))
    Q11 = tf.multiply(tf.tile(tf.reshape(weights, [-1, 1]), [1, dim]), Q11)

    weights = tf.multiply(tf.subtract(x, x1), tf.subtract(y2, y))
    Q21 = tf.multiply(tf.tile(tf.reshape(weights, [-1, 1]), [1, dim]), Q21)

    weights = tf.multiply(tf.subtract(x2, x), tf.subtract(y, y1))
    Q12 = tf.multiply(tf.tile(tf.reshape(weights, [-1, 1]), [1, dim]), Q12)

    weights = tf.multiply(tf.subtract(x, x1), tf.subtract(y, y1))
    Q22 = tf.multiply(tf.tile(tf.reshape(weights, [-1, 1]), [1, dim]), Q22)

    outputs = tf.add_n([Q11, Q21, Q12, Q22])
    return outputs

```

**Comment by Sayan-m90** [comment]
Solved it thanks to tensorflow gpu. Here is what I did: 
`conda create --name pixmesh tensorflow-gpu=1  python=2.7`
then pip install tflearn

**Comment by lzw365-code** [comment]
Hi, I am trying to run this on colab, and when I use python2 -m pip install tensorflow==1.3.0, I got the same issue, and when I tried to use python2 -m pip install tensorflow-gpu==1.3.0, I got a new error like the following, so does anyone succeeded in training this model and know how to solve this problem, or what version of TensorFlow I should use, thanks:

Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Michael-H1302** [comment]
@lzw365-code I run into the same issue and was able to resolve it by install cudnn6 (below is the only direct download link i found):

!wget https://developer.download.nvidia.com/compute/redist/cudnn/v6.0/libcudnn6_6.0.20-1+cuda7.5_amd64.deb
!sudo apt install ./libcudnn6_6.0.20-1+cuda7.5_amd64.deb

After installing cudnn I run into the same problem again. The solution is to remove the 22th line in the train.py file which selects the cuda device

os.environ['CUDA_VISIBLE_DEVICES'] = '1'

The line caused cuda to not find a valid device and therefore fall back to cpu functionality.
