### ISSUE TITLE
undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by abadcd** [nywang16/Pixel2Mesh#45]
When I solved the _ZTIN10tensorflow8OpKernelE_ problem, I encountered a new problem _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv, if you know please tell me, thank you very much

This is my mistake：
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from pixel2mesh.models import GCN
  File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 3, in <module>
    from pixel2mesh.losses import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 2, in <module>
    from pixel2mesh.cd_dist import *
  File "build/bdist.linux-x86_64/egg/pixel2mesh/cd_dist.py", line 3, in <module>
    nn_distance_module=tf.load_op_library('./external/tf_nndistance_so.so')
  File "/home/software/anaconda/envs/tensorflow-gpu/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./external/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

**Comment by abadcd** [comment]
I solved it
If you have the same problem, this is probably related to the gcc version. Check out the gcc version, gcc=5.x to use conda install tensorflow, gcc=4.x to use pip install tensorflow, because the tensorflow installed by pip may be Gcc4 compiled.
If it is wrong, please indicate.

**Comment by bodhicheng** [comment]
The problem is caused by the difference between the local and compiled gcc versions of tensorflow.
Conda's tensorflow is compiled by gcc7. My local version is 4.8. When I installed with pip, the problem was solved.

**Comment by wanqunAmy** [comment]
> I solved it
> If you have the same problem, this is probably related to the gcc version. Check out the gcc version, gcc=5.x to use conda install tensorflow, gcc=4.x to use pip install tensorflow, because the tensorflow installed by pip may be Gcc4 compiled.
> If it is wrong, please indicate.

hi，I dont understand how to solve? help?

**Comment by anguyen216** [comment]
@abadcd How did you solve the ZTIN10tensorflow8OpKernelE problem? I'm encountering the same problem when trying to compile the functions on Google Colab (cuda 10.1, python 3.7, tensorflow 1.15.2)
