### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by WangDYYY** [nywang16/Pixel2Mesh#82]
Traceback (most recent call last):
  File "demo.py", line 70, in <module>
    model.load(sess)
  File "/home/wangdyyy/workspace/Pixel2Mesh/p2m/api.py", line 109, in load
    saver.restore(sess, save_path)
  File "/home/wangdyyy/workspace/Pixel2Mesh/p2m/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/wangdyyy/workspace/Pixel2Mesh/p2m/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/wangdyyy/workspace/Pixel2Mesh/p2m/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wangdyyy/workspace/Pixel2Mesh/p2m/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/wangdyyy/workspace/Pixel2Mesh/p2m/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256,256] rhs shape= [192,192]
         [[Node: save/Assign_164 = Assign[T=DT_FLOAT, _class=["loc:@gcn/graphconvolution_9_vars/weights_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](gcn/graphconvolution_9_vars/weights_1, save/RestoreV2_164)]]

**Comment by seawardhai** [comment]
Hello, has your problem been solved? Like you, I have encountered the same problem and can't be solved

**Comment by seawardhai** [comment]
Hello, has your problem been solved? Like you, I have encountered the same problem and can't be solved
