### ISSUE TITLE
build_cnn18 - inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by tomaszjacek** [nywang16/Pixel2Mesh#84]
Hi All,

I'm getting an error

Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    from p2m.api import GCN
  File "G:\addOns\Pixel2Mesh-master\p2m\api.py", line 180
    x=self.placeholders['img_inp']
                                                  ^
TabError: inconsistent use of tabs and spaces in indentation

when I removed '] from line x=self.placeholders['img_inp'] and writed it again
I have

Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    from p2m.api import GCN
  File "G:\addOns\Pixel2Mesh-master\p2m\api.py", line 181
    x = tf.expand_dims(x, 0)
                                        ^
TabError: inconsistent use of tabs and spaces in indentation

Do you have an idea what could be wrong?

Thank you,

tj

**Comment by MrMois** [comment]
Hello, I have the same problem, as shown in the error message the code uses tab characters and softtabs (4 tabs in a row) for indentation. This is not allowed by python, I wrote a script which you find below. It fixes the error by replacing the tabs. Simply run it from the repo root folder (where demo.py is located). But I highly recommend you to not use this code, as it uses deprecated old Tensorflow and old Python 2.7. 
There are newer implementations using pytorch: https://github.com/noahcao/Pixel2Mesh and https://github.com/Tong-ZHAO/Pixel2Mesh-Pytorch
But fixing this code would be nice as above code is only available to CUDA as it seems.
Greetings, MrMois

Script:

import os

NUMSPACES = 4

for (path, dirs, files) in os.walk('.'):

    for file in files:

        if(file[-3:] == '.py'):

            print('Currently at: %s\\%s' % (path, file))

            str = ''

            with open(path + '\\' + file, 'r+') as fHandle:

                str = fHandle.read()

                if '\t' in str:

                    if '  ' in str:
                        print('Found tabs and doublespaces, yay!')
                    else:
                        print('Found tabs...')

                    str = str.replace('\t', ' ' * NUMSPACES)

                    # Goto file start
                    fHandle.seek(0)
                    fHandle.write(str)

                    print('Replaces tabs with %i whitespaces.' % NUMSPACES)

                else:
                    print('Ok.')

            print('---------')

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it?
